---
title: Rob Southgate
timezone: UTC
collections:
  ar_effects:
    title: Ar effects
    output: true
    permalink: "/ar-effects/:name"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:name"
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: 
twitter_username: rsouth90
github_username: robsouthgate4
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
sass:
  sass_dir: _scss
